In [3]:
import pandas as pd

In [4]:
import sqlalchemy as sa

In [5]:
import requests

In [6]:
source='InciWeb,EO'
status='open'
days=20

In [7]:
api_url = 'https://eonet.gsfc.nasa.gov/api/v2.1/events?source={}&status={}&days={}'.format(source,status,days)

In [8]:
print(api_url)

https://eonet.gsfc.nasa.gov/api/v2.1/events?source=InciWeb,EO&status=open&days=20

In [9]:
api_response=requests.get(api_url)

In [10]:
events = api_response.json()
events

{'title': 'EONET Events',
 'description': 'Natural events from EONET.',
 'link': 'https://eonet.gsfc.nasa.gov/api/v2.1/events',
 'events': [{'id': 'EONET_4031',
   'title': 'Iceberg B46',
   'description': '',
   'link': 'https://eonet.gsfc.nasa.gov/api/v2.1/events/EONET_4031',
   'categories': [{'id': 15, 'title': 'Sea and Lake Ice'}],
   'sources': [{'id': 'EO',
     'url': 'https://earthobservatory.nasa.gov/images/144212/pine-island-glacier-quickly-drops-another-iceberg'},
    {'id': 'NATICE',
     'url': 'https://usicecenter.gov/pub/Iceberg_Tabular.csv'}],
   'geometries': [{'date': '2018-11-09T00:00:00Z',
     'type': 'Point',
     'coordinates': [-101.27, -75.04]},
    {'date': '2019-02-01T00:00:00Z',
     'type': 'Point',
     'coordinates': [-103.95, -74.78]},
    {'date': '2019-08-02T00:00:00Z',
     'type': 'Point',
     'coordinates': [-105.03, -74.31]},
    {'date': '2020-09-18T00:00:00Z',
     'type': 'Point',
     'coordinates': [-106.65, -74.09]},
    {'date': '2020-10-16T00:00:00Z',
     'type': 'Point',
     'coordinates': [-107.55, -73.63]},
    {'date': '2020-12-04T00:00:00Z',
     'type': 'Point',
     'coordinates': [-108.01, -73.01]},
    {'date': '2021-02-19T00:00:00Z',
     'type': 'Point',
     'coordinates': [-111.47, -72.57]},
    {'date': '2021-04-23T00:00:00Z',
     'type': 'Point',
     'coordinates': [-112.74, -72.31]},
    {'date': '2021-06-18T00:00:00Z',
     'type': 'Point',
     'coordinates': [-114.28, -72.65]},
    {'date': '2021-07-09T00:00:00Z',
     'type': 'Point',
     'coordinates': [-117.04, -72.14]},
    {'date': '2021-07-16T00:00:00Z',
     'type': 'Point',
     'coordinates': [-118.54, -72.22]},
    {'date': '2021-07-23T00:00:00Z',
     'type': 'Point',
     'coordinates': [-120.26, -72.47]},
    {'date': '2021-07-30T00:00:00Z',
     'type': 'Point',
     'coordinates': [-121.97, -72.39]},
    {'date': '2021-09-03T00:00:00Z',
     'type': 'Point',
     'coordinates': [-124.17, -72.06]},
    {'date': '2021-09-10T00:00:00Z',
     'type': 'Point',
     'coordinates': [-125.78, -71.9]},
    {'date': '2021-09-24T00:00:00Z',
     'type': 'Point',
     'coordinates': [-127.77, -71.98]},
    {'date': '2021-10-08T00:00:00Z',
     'type': 'Point',
     'coordinates': [-130.7, -72.52]},
    {'date': '2021-10-22T00:00:00Z',
     'type': 'Point',
     'coordinates': [-132.72, -72.78]},
    {'date': '2021-11-12T00:00:00Z',
     'type': 'Point',
     'coordinates': [-133.44, -72.12]},
    {'date': '2022-03-04T00:00:00Z',
     'type': 'Point',
     'coordinates': [-133.6, -71.64]},
    {'date': '2022-03-25T00:00:00Z',
     'type': 'Point',
     'coordinates': [-132.36, -71.4]},
    {'date': '2022-04-22T00:00:00Z',
     'type': 'Point',
     'coordinates': [-132.51, -72.0]},
    {'date': '2022-05-06T00:00:00Z',
     'type': 'Point',
     'coordinates': [-134.52, -72.49]},
    {'date': '2022-05-13T00:00:00Z',
     'type': 'Point',
     'coordinates': [-136.84, -72.65]},
    {'date': '2022-05-27T00:00:00Z',
     'type': 'Point',
     'coordinates': [-137.82, -73.3]},
    {'date': '2022-06-17T00:00:00Z',
     'type': 'Point',
     'coordinates': [-139.64, -73.63]},
    {'date': '2022-07-08T00:00:00Z',
     'type': 'Point',
     'coordinates': [-145.18, -74.31]},
    {'date': '2022-07-15T00:00:00Z',
     'type': 'Point',
     'coordinates': [-147.85, -74.75]},
    {'date': '2022-07-29T00:00:00Z',
     'type': 'Point',
     'coordinates': [-149.47, -74.98]},
    {'date': '2022-08-12T00:00:00Z',
     'type': 'Point',
     'coordinates': [-153.37, -75.09]},
    {'date': '2022-08-26T00:00:00Z',
     'type': 'Point',
     'coordinates': [-155.02, -74.43]},
    {'date': '2022-09-09T00:00:00Z',
     'type': 'Point',
     'coordinates': [-155.68, -73.55]},
    {'date': '2022-09-23T00:00:00Z',
     'type': 'Point',
     'coordinates': [-156.82, -73.23]},
    {'date': '2022-10-07T00:00:00Z',
     'type': 'Point',
     'coordinates': [-157.6, -72.41]},
    {'date': '2022-10-21T00:00:00Z',
     'type': 'Point',
     'coordinates': [-157.45, -71.39]},
    {'date': '2022-11-04T00:00:00Z',
     'type': 'Point',
     'coordinates': [-159.45, -71.5]},
    {'date': '2022-11-18T00:00:00Z',
     'type': 'Point',
     'coordinates': [-160.27, -71.12]},
    {'date': '2022-11-25T00:00:00Z',
     'type': 'Point',
     'coordinates': [-159.2, -70.74]},
    {'date': '2022-12-02T00:00:00Z',
     'type': 'Point',
     'coordinates': [-157.88, -70.39]},
    {'date': '2022-12-23T00:00:00Z',
     'type': 'Point',
     'coordinates': [-156.24, -70.05]},
    {'date': '2022-12-30T00:00:00Z',
     'type': 'Point',
     'coordinates': [-157.21, -69.53]},
    {'date': '2023-02-10T00:00:00Z',
     'type': 'Point',
     'coordinates': [-159.06, -69.48]},
    {'date': '2023-03-31T00:00:00Z',
     'type': 'Point',
     'coordinates': [-157.74, -69.03]},
    {'date': '2023-04-28T00:00:00Z',
     'type': 'Point',
     'coordinates': [-158.86, -68.59]},
    {'date': '2023-05-19T00:00:00Z',
     'type': 'Point',
     'coordinates': [-158.53, -68.11]},
    {'date': '2023-06-09T00:00:00Z',
     'type': 'Point',
     'coordinates': [-157.43, -67.72]},
    {'date': '2023-06-30T00:00:00Z',
     'type': 'Point',
     'coordinates': [-156.15, -66.79]},
    {'date': '2023-07-07T00:00:00Z',
     'type': 'Point',
     'coordinates': [-155.47, -67.25]},
    {'date': '2023-07-14T00:00:00Z',
     'type': 'Point',
     'coordinates': [-154.69, -66.83]},
    {'date': '2023-07-28T00:00:00Z',
     'type': 'Point',
     'coordinates': [-158.29, -67.95]}]},
  {'id': 'EONET_4440',
   'title': 'Iceberg D28',
   'description': '',
   'link': 'https://eonet.gsfc.nasa.gov/api/v2.1/events/EONET_4440',
   'categories': [{'id': 15, 'title': 'Sea and Lake Ice'}],
   'sources': [{'id': 'EO',
     'url': 'https://earthobservatory.nasa.gov/images/145680/rifting-and-calving-on-the-amery-ice-shelf'},
    {'id': 'NATICE',
     'url': 'https://usicecenter.gov/pub/Iceberg_Tabular.csv'}],
   'geometries': [{'date': '2019-09-27T00:00:00Z',
     'type': 'Point',
     'coordinates': [72.21, -68.55]},
    {'date': '2019-10-18T00:00:00Z',
     'type': 'Point',
     'coordinates': [70.99, -68.32]},
    {'date': '2020-01-24T00:00:00Z',
     'type': 'Point',
     'coordinates': [71.24, -67.86]},
    {'date': '2020-02-21T00:00:00Z',
     'type': 'Point',
     'coordinates': [72.02, -67.37]},
    {'date': '2020-03-13T00:00:00Z',
     'type': 'Point',
     'coordinates': [73.25, -67.36]},
    {'date': '2020-04-03T00:00:00Z',
     'type': 'Point',
     'coordinates': [74.07, -67.02]},
    {'date': '2020-04-17T00:00:00Z',
     'type': 'Point',
     'coordinates': [73.35, -66.57]},
    {'date': '2020-05-01T00:00:00Z',
     'type': 'Point',
     'coordinates': [71.85, -66.31]},
    {'date': '2020-05-15T00:00:00Z',
     'type': 'Point',
     'coordinates': [69.81, -66.66]},
    {'date': '2020-05-22T00:00:00Z',
     'type': 'Point',
     'coordinates': [68.44, -66.87]},
    {'date': '2020-06-05T00:00:00Z',
     'type': 'Point',
     'coordinates': [65.87, -66.74]},
    {'date': '2020-06-12T00:00:00Z',
     'type': 'Point',
     'coordinates': [64.69, -66.66]},
    {'date': '2020-06-26T00:00:00Z',
     'type': 'Point',
     'coordinates': [62.81, -66.5]},
    {'date': '2020-07-03T00:00:00Z',
     'type': 'Point',
     'coordinates': [61.52, -66.47]},
    {'date': '2020-07-17T00:00:00Z',
     'type': 'Point',
     'coordinates': [59.99, -66.58]},
    {'date': '2020-08-28T00:00:00Z',
     'type': 'Point',
     'coordinates': [58.98, -66.38]},
    {'date': '2020-09-25T00:00:00Z',
     'type': 'Point',
     'coordinates': [57.88, -65.92]},
    {'date': '2020-10-16T00:00:00Z',
     'type': 'Point',
     'coordinates': [56.31, -65.57]},
    {'date': '2020-11-20T00:00:00Z',
     'type': 'Point',
     'coordinates': [55.2, -65.43]},
    {'date': '2021-02-19T00:00:00Z',
     'type': 'Point',
     'coordinates': [49.33, -66.18]},
    {'date': '2021-03-05T00:00:00Z',
     'type': 'Point',
     'coordinates': [47.35, -66.32]},
    {'date': '2021-03-19T00:00:00Z',
     'type': 'Point',
     'coordinates': [45.85, -66.85]},
    {'date': '2021-03-26T00:00:00Z',
     'type': 'Point',
     'coordinates': [44.73, -66.99]},
    {'date': '2021-04-02T00:00:00Z',
     'type': 'Point',
     'coordinates': [43.56, -67.26]},
    {'date': '2021-04-16T00:00:00Z',
     'type': 'Point',
     'coordinates': [40.97, -67.77]},
    {'date': '2021-04-23T00:00:00Z',
     'type': 'Point',
     'coordinates': [39.42, -68.16]},
    {'date': '2021-04-30T00:00:00Z',
     'type': 'Point',
     'coordinates': [37.23, -68.18]},
    {'date': '2021-05-07T00:00:00Z',
     'type': 'Point',
     'coordinates': [34.52, -67.97]},
    {'date': '2021-05-14T00:00:00Z',
     'type': 'Point',
     'coordinates': [32.93, -68.2]},
    {'date': '2021-05-21T00:00:00Z',
     'type': 'Point',
     'coordinates': [30.8, -68.73]},
    {'date': '2021-05-28T00:00:00Z',
     'type': 'Point',
     'coordinates': [27.11, -69.51]},
    {'date': '2021-06-04T00:00:00Z',
     'type': 'Point',
     'coordinates': [24.73, -69.82]},
    {'date': '2021-06-11T00:00:00Z',
     'type': 'Point',
     'coordinates': [20.78, -69.69]},
    {'date': '2021-06-18T00:00:00Z',
     'type': 'Point',
     'coordinates': [17.66, -69.33]},
    {'date': '2021-06-25T00:00:00Z',
     'type': 'Point',
     'coordinates': [15.52, -69.08]},
    {'date': '2021-07-02T00:00:00Z',
     'type': 'Point',
     'coordinates': [13.5, -69.1]},
    {'date': '2021-07-16T00:00:00Z',
     'type': 'Point',
     'coordinates': [11.38, -69.25]},
    {'date': '2021-07-30T00:00:00Z',
     'type': 'Point',
     'coordinates': [8.37, -69.52]},
    {'date': '2021-08-06T00:00:00Z',
     'type': 'Point',
     'coordinates': [6.15, -69.82]},
    {'date': '2021-08-13T00:00:00Z',
     'type': 'Point',
     'coordinates': [4.34, -69.89]},
    {'date': '2021-08-20T00:00:00Z',
     'type': 'Point',
     'coordinates': [1.09, -69.54]},
    {'date': '2021-08-27T00:00:00Z',
     'type': 'Point',
     'coordinates': [-1.7, -69.43]},
    {'date': '2021-09-03T00:00:00Z',
     'type': 'Point',
     'coordinates': [-3.95, -69.92]},
    {'date': '2021-09-10T00:00:00Z',
     'type': 'Point',
     'coordinates': [-6.09, -70.0]},
    {'date': '2021-09-17T00:00:00Z',
     'type': 'Point',
     'coordinates': [-7.51, -70.19]},
    {'date': '2021-09-24T00:00:00Z',
     'type': 'Point',
     'coordinates': [-9.61, -70.43]},
    {'date': '2021-10-01T00:00:00Z',
     'type': 'Point',
     'coordinates': [-10.99, -70.61]},
    {'date': '2021-10-08T00:00:00Z',
     'type': 'Point',
     'coordinates': [-12.15, -70.86]},
    {'date': '2021-10-22T00:00:00Z',
     'type': 'Point',
     'coordinates': [-15.28, -71.37]},
    {'date': '2021-11-12T00:00:00Z',
     'type': 'Point',
     'coordinates': [-18.73, -72.43]},
    {'date': '2022-02-04T00:00:00Z',
     'type': 'Point',
     'coordinates': [-26.78, -74.1]},
    {'date': '2022-02-25T00:00:00Z',
     'type': 'Point',
     'coordinates': [-28.16, -74.51]},
    {'date': '2022-03-25T00:00:00Z',
     'type': 'Point',
     'coordinates': [-30.15, -74.43]},
    {'date': '2022-04-15T00:00:00Z',
     'type': 'Point',
     'coordinates': [-32.3, -74.52]},
    {'date': '2022-05-20T00:00:00Z',
     'type': 'Point',
     'coordinates': [-34.96, -74.35]},
    {'date': '2022-06-03T00:00:00Z',
     'type': 'Point',
     'coordinates': [-37.72, -74.26]},
    {'date': '2022-06-17T00:00:00Z',
     'type': 'Point',
     'coordinates': [-39.89, -74.4]},
    {'date': '2022-07-01T00:00:00Z',
     'type': 'Point',
     'coordinates': [-41.56, -73.97]},
    {'date': '2022-07-15T00:00:00Z',
     'type': 'Point',
     'coordinates': [-42.69, -73.37]},
    {'date': '2022-08-12T00:00:00Z',
     'type': 'Point',
     'coordinates': [-43.81, -73.0]},
    {'date': '2022-09-09T00:00:00Z',
     'type': 'Point',
     'coordinates': [-46.13, -72.52]},
    {'date': '2022-09-23T00:00:00Z',
     'type': 'Point',
     'coordinates': [-47.48, -72.18]},
    {'date': '2022-10-14T00:00:00Z',
     'type': 'Point',
     'coordinates': [-48.98, -72.02]},
    {'date': '2022-10-28T00:00:00Z',
     'type': 'Point',
     'coordinates': [-50.61, -71.86]},
    {'date': '2022-11-11T00:00:00Z',
     'type': 'Point',
     'coordinates': [-52.41, -71.72]},
    {'date': '2022-12-02T00:00:00Z',
     'type': 'Point',
     'coordinates': [-54.09, -71.39]},
    {'date': '2022-12-16T00:00:00Z',
     'type': 'Point',
     'coordinates': [-55.54, -70.87]},
    {'date': '2022-12-30T00:00:00Z',
     'type': 'Point',
     'coordinates': [-56.11, -70.39]},
    {'date': '2023-01-20T00:00:00Z',
     'type': 'Point',
     'coordinates': [-55.69, -69.66]},
    {'date': '2023-02-10T00:00:00Z',
     'type': 'Point',
     'coordinates': [-55.55, -69.15]},
    {'date': '2023-03-24T00:00:00Z',
     'type': 'Point',
     'coordinates': [-55.18, -68.56]},
    {'date': '2023-04-07T00:00:00Z',
     'type': 'Point',
     'coordinates': [-55.15, -68.05]},
    {'date': '2023-04-21T00:00:00Z',
     'type': 'Point',
     'coordinates': [-55.29, -67.39]},
    {'date': '2023-04-28T00:00:00Z',
     'type': 'Point',
     'coordinates': [-55.1, -66.86]},
    {'date': '2023-05-12T00:00:00Z',
     'type': 'Point',
     'coordinates': [-54.52, -65.94]},
    {'date': '2023-06-02T00:00:00Z',
     'type': 'Point',
     'coordinates': [-54.06, -65.0]},
    {'date': '2023-06-15T00:00:00Z',
     'type': 'Point',
     'coordinates': [-53.91, -64.13]},
    {'date': '2023-06-23T00:00:00Z',
     'type': 'Point',
     'coordinates': [-54.06, -65]},
    {'date': '2023-06-30T00:00:00Z',
     'type': 'Point',
     'coordinates': [-53.87, -62.68]},
    {'date': '2023-07-07T00:00:00Z',
     'type': 'Point',
     'coordinates': [-53.88, -62.14]},
    {'date': '2023-07-14T00:00:00Z',
     'type': 'Point',
     'coordinates': [-53.12, -61.81]},
    {'date': '2023-07-28T00:00:00Z',
     'type': 'Point',
     'coordinates': [-54.06, -65.0]}]},
  {'id': 'EONET_6388',
   'title': 'Flat Fire Information',
   'description': '',
   'link': 'https://eonet.gsfc.nasa.gov/api/v2.1/events/EONET_6388',
   'categories': [{'id': 8, 'title': 'Wildfires'}],
   'sources': [{'id': 'InciWeb',
     'url': 'http://inciweb.nwcg.gov/incident-information/xx1002-flat-fire'}],
   'geometries': [{'date': '2023-07-15T21:51:00Z',
     'type': 'Point',
     'coordinates': [-124.0372, 42.5158]}]}]}

In [11]:
df = pd.DataFrame(events['events'])

In [12]:
df

,id,title,description,link,categories,sources,geometries
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","[{'date': '2018-11-09T00:00:00Z', 'type': 'Poi..."
1,EONET_4440,Iceberg D28,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","[{'date': '2019-09-27T00:00:00Z', 'type': 'Poi..."
2,EONET_6388,Flat Fire Information,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 8, 'title': 'Wildfires'}]","[{'id': 'InciWeb', 'url': 'http://inciweb.nwcg...","[{'date': '2023-07-15T21:51:00Z', 'type': 'Poi..."

In [13]:
df = df.explode('geometries')

In [14]:
df

,id,title,description,link,categories,sources,geometries
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","{'date': '2018-11-09T00:00:00Z', 'type': 'Poin..."
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","{'date': '2019-02-01T00:00:00Z', 'type': 'Poin..."
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","{'date': '2019-08-02T00:00:00Z', 'type': 'Poin..."
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","{'date': '2020-09-18T00:00:00Z', 'type': 'Poin..."
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","{'date': '2020-10-16T00:00:00Z', 'type': 'Poin..."
...,...,...,...,...,...,...,...
1,EONET_4440,Iceberg D28,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","{'date': '2023-06-30T00:00:00Z', 'type': 'Poin..."
1,EONET_4440,Iceberg D28,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","{'date': '2023-07-07T00:00:00Z', 'type': 'Poin..."
1,EONET_4440,Iceberg D28,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","{'date': '2023-07-14T00:00:00Z', 'type': 'Poin..."
1,EONET_4440,Iceberg D28,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...","{'date': '2023-07-28T00:00:00Z', 'type': 'Poin..."
2,EONET_6388,Flat Fire Information,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 8, 'title': 'Wildfires'}]","[{'id': 'InciWeb', 'url': 'http://inciweb.nwcg...","{'date': '2023-07-15T21:51:00Z', 'type': 'Poin..."

In [15]:
df_geometries = df['geometries'].apply(pd.Series)

# Now, let's concatenate this data back to our original dataframe
df = pd.concat([df.drop(['geometries'], axis=1), df_geometries], axis=1)

In [16]:
df

,id,title,description,link,categories,sources,date,type,coordinates
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...",2018-11-09T00:00:00Z,Point,"[-101.27, -75.04]"
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...",2019-02-01T00:00:00Z,Point,"[-103.95, -74.78]"
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...",2019-08-02T00:00:00Z,Point,"[-105.03, -74.31]"
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...",2020-09-18T00:00:00Z,Point,"[-106.65, -74.09]"
0,EONET_4031,Iceberg B46,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...",2020-10-16T00:00:00Z,Point,"[-107.55, -73.63]"
...,...,...,...,...,...,...,...,...,...
1,EONET_4440,Iceberg D28,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...",2023-06-30T00:00:00Z,Point,"[-53.87, -62.68]"
1,EONET_4440,Iceberg D28,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...",2023-07-07T00:00:00Z,Point,"[-53.88, -62.14]"
1,EONET_4440,Iceberg D28,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...",2023-07-14T00:00:00Z,Point,"[-53.12, -61.81]"
1,EONET_4440,Iceberg D28,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 15, 'title': 'Sea and Lake Ice'}]","[{'id': 'EO', 'url': 'https://earthobservatory...",2023-07-28T00:00:00Z,Point,"[-54.06, -65.0]"
2,EONET_6388,Flat Fire Information,,https://eonet.gsfc.nasa.gov/api/v2.1/events/EO...,"[{'id': 8, 'title': 'Wildfires'}]","[{'id': 'InciWeb', 'url': 'http://inciweb.nwcg...",2023-07-15T21:51:00Z,Point,"[-124.0372, 42.5158]"

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133 entries, 0 to 2
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           133 non-null    object
 1   title        133 non-null    object
 2   description  133 non-null    object
 3   link         133 non-null    object
 4   categories   133 non-null    object
 5   sources      133 non-null    object
 6   date         133 non-null    object
 7   type         133 non-null    object
 8   coordinates  133 non-null    object
dtypes: object(9)
memory usage: 10.4+ KB

In [18]:
df['date']=pd.to_datetime(df['date'])

In [19]:
relevant_col = ['title','date','coordinates']

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133 entries, 0 to 2
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           133 non-null    object
 1   title        133 non-null    object
 2   description  133 non-null    object
 3   link         133 non-null    object
 4   categories   133 non-null    object
 5   sources      133 non-null    object
 6   date         133 non-null    datetime64[ns, UTC]
 7   type         133 non-null    object
 8   coordinates  133 non-null    object
dtypes: datetime64[ns, UTC](1), object(8)
memory usage: 10.4+ KB

In [21]:
final_df = df[relevant_col]

In [22]:
final_df

                    title                      date           coordinates
0             Iceberg B46 2018-11-09 00:00:00+00:00     [-101.27, -75.04]
0             Iceberg B46 2019-02-01 00:00:00+00:00     [-103.95, -74.78]
0             Iceberg B46 2019-08-02 00:00:00+00:00     [-105.03, -74.31]
0             Iceberg B46 2020-09-18 00:00:00+00:00     [-106.65, -74.09]
0             Iceberg B46 2020-10-16 00:00:00+00:00     [-107.55, -73.63]
..                    ...                       ...                   ...
1             Iceberg D28 2023-06-30 00:00:00+00:00      [-53.87, -62.68]
1             Iceberg D28 2023-07-07 00:00:00+00:00      [-53.88, -62.14]
1             Iceberg D28 2023-07-14 00:00:00+00:00      [-53.12, -61.81]
1             Iceberg D28 2023-07-28 00:00:00+00:00       [-54.06, -65.0]
2   Flat Fire Information 2023-07-15 21:51:00+00:00  [-124.0372, 42.5158]

[133 rows x 3 columns]

In [23]:
final_df[['longitude', 'latitude']] = pd.DataFrame(df['coordinates'].tolist(), index=df.index)
final_df = final_df.drop(columns=['coordinates'])

/var/folders/sd/qxcy57pn3lx8ny384gzv1w5r0000gn/T/ipykernel_1354/2992153962.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[['longitude', 'latitude']] = pd.DataFrame(df['coordinates'].tolist(), index=df.index)
/var/folders/sd/qxcy57pn3lx8ny384gzv1w5r0000gn/T/ipykernel_1354/2992153962.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[['longitude', 'latitude']] = pd.DataFrame(df['coordinates'].tolist(), index=df.index)

In [26]:
final_df

                    title                      date  longitude  latitude
0             Iceberg B46 2018-11-09 00:00:00+00:00  -101.2700  -75.0400
0             Iceberg B46 2019-02-01 00:00:00+00:00  -103.9500  -74.7800
0             Iceberg B46 2019-08-02 00:00:00+00:00  -105.0300  -74.3100
0             Iceberg B46 2020-09-18 00:00:00+00:00  -106.6500  -74.0900
0             Iceberg B46 2020-10-16 00:00:00+00:00  -107.5500  -73.6300
..                    ...                       ...        ...       ...
1             Iceberg D28 2023-06-30 00:00:00+00:00   -53.8700  -62.6800
1             Iceberg D28 2023-07-07 00:00:00+00:00   -53.8800  -62.1400
1             Iceberg D28 2023-07-14 00:00:00+00:00   -53.1200  -61.8100
1             Iceberg D28 2023-07-28 00:00:00+00:00   -54.0600  -65.0000
2   Flat Fire Information 2023-07-15 21:51:00+00:00  -124.0372   42.5158

[133 rows x 4 columns]

In [25]:
db_secret={
    'drivername': 'postgresql+psycopg2',
    'host':'mmai5100postgres.canadacentral.cloudapp.azure.com',
    'port':'5432',
    'user':'rupaliw',
    'password':'2023!Schulich',
    'database':'rupaliw_db'
}
db_connection_url = sa.engine.URL.create(
    drivername = db_secret['drivername'],
    username = db_secret['user'],
    password = db_secret['password'],#don't use password in a company, security issue
    host = db_secret['host'],
    port = db_secret['port'],
    database = db_secret['database']
)
engine = sa.create_engine(db_connection_url)
with engine.connect() as connection:
    connection.execute('CREATE SCHEMA IF NOT EXISTS project_db')
    final_df.to_sql(
name='Events_NASA',#table name
schema='project_db',
con = engine,
if_exists ='replace',
    index=False,
    method='multi',
    dtype={
        'title':sa.types.String,
        'date':sa.type.DATE,
        'latitude':sa.types.DECIMAL(10,0),
        'longitude':sa.types.DECIMAL(10,0)
    }
)

ModuleNotFoundError: No module named 'psycopg2'

In [28]:
final_df.isna().any().any()

False